version: '3.8'

services:
  back-end:
    build:
      context: .
      dockerfile: compose/back-end/Dockerfile
      args:
        - UID=$MYUID
        - GID=$MYGID
    image: back-end
    container_name: back-end
    environment:
      - PYTHONPATH=/app/src/tabs_organizer
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: /start