# Generated by Django 5.0.6 on 2024-07-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songbook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="structure",
            field=models.TextField(
                default="", help_text="Comma-separated list of song sections"
            ),
            preserve_default=False,
        ),
    ]
